### ISSUE TITLE
Nodejs, handle stack trace

### ISSUE THREAD

**Issue by jsirianni** [observIQ/stanza-plugins#313]
Nodejs uses json logging, however, stacktraces show up like this
```
Error: Member does not exist
    at /app/app.js:31:15
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at param (/app/node_modules/express/lib/router/index.js:354:14)
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
```

Each line is treated as an individual entry

**Comment by ericwholt** [comment]
I haven't found a good way to handle this through a plugin at this time. The issue is when you have a multiline log entry and single line log entry in the same log file. Unless they have distinct line start patterns there is not way to tell between the two types of logs. 

A JSON log entry isn't suited for a good line start pattern as you can have nested json elements.
